// StarEvents/Services/QRCodeService.cs
using System;
using System.Drawing;
using System.IO;
using QRCoder;
using StarEvents.Models; // Ensure this is correct for your Ticket and Booking models
using StarEvents.Services; // Ensure this matches your namespace structure

namespace StarEvents.Services
{
    // The class must implement IQRCodeService
    public class QRCodeService : IQRCodeService
    {
        /// <summary>
        /// Generates the raw, unique string data to be encoded in the QR code.
        /// Format: TicketNumber|BookingReference|EventId
        /// </summary>
        /// <param name="ticket">The Ticket model instance.</param>
        /// <returns>A formatted string for QR code encoding.</returns>
        public string GenerateTicketData(Ticket ticket)
        {
            // IMPORTANT: If 'ticket.Booking' is null, the booking has not been fully loaded or saved correctly.
            // We use the available IDs to create a fallback string, but the full reference is preferred.
            if (ticket.Booking == null)
            {
                // Fallback using BookingId
                return $"TKT-{ticket.TicketNumber}|BOOKING-ID-{ticket.BookingId}|EVENT-UNKNOWN";
            }

            // This is the preferred and secure data format
            return $"{ticket.TicketNumber}|{ticket.Booking.BookingReference}|{ticket.Booking.EventId}";
        }

        /// <summary>
        /// Generates the QR code image and converts it to a Base64 string for storage/display.
        /// </summary>
        /// <param name="data">The raw string data generated by GenerateTicketData.</param>
        /// <returns>A Base64 string prefixed for direct use in an HTML <img> tag.</returns>
        public string GenerateQRCodeBase64(string data)
        {
            if (string.IsNullOrEmpty(data))
            {
                return string.Empty;
            }

            // Using QRCoder library to generate the QR code
            using (var generator = new QRCodeGenerator())
            {
                // ECCLevel.Q (Quarter) offers good balance of error correction and data density
                var qrCodeData = generator.CreateQrCode(data, QRCodeGenerator.ECCLevel.Q);

                using (var qrCode = new QRCode(qrCodeData))
                {
                    // GetGraphic generates the Bitmap image. 
                    // The argument '10' is the pixels per module (size).
                    using (Bitmap qrCodeImage = qrCode.GetGraphic(10, Color.Black, Color.White, true))
                    {
                        using (MemoryStream ms = new MemoryStream())
                        {
                            // Save the image to a MemoryStream as a PNG
                            qrCodeImage.Save(ms, System.Drawing.Imaging.ImageFormat.Png);

                            // Convert to Base64 string and prefix it for HTML display (data URI scheme)
                            return "data:image/png;base64," + Convert.ToBase64String(ms.ToArray());
                        }
                    }
                }
            }
        }
    }
}